services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-password}
      - POSTGRES_DB=${PG_PASSWORD:-db}
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./data:/data
